@startuml
!define FILE_ICON <img src="https://raw.githubusercontent.com/PlantUML-Icons/PlantUML-icons/af9193a5161db3496f11437f8b6b1225

package "HTML Code" {
  component "<!DOCTYPE html>" as html
  component "css/bootstrap.css" as bootstrap
  component "style.css" as style
  component "visualization.css" as visualization
}

package "Components" {
  component "nav.navbar" as navbar
  component "div.container-fluid" as containerFluid
  component "div.collapse.navbar" as navbarCollapse
  component "div.container" as container
  component "span" as span
  component "p" as p
}

package "Images" {
  component "data/Product quality-amico.png"
}

html --> bootstrap
html --> style
html --> visualization

navbar --> containerFluid
containerFluid --> navbarCollapse
navbarCollapse --> container
container --> span
container --> p

@enduml
